Add metro plugin support for @rnx-kit/third-party-notices
microsoft/rnx-kit pull request #2127
Opened 2023-01-18 14:53 UTC by AAHAbbas

### Description

Adding metro plugin support for @rnx-kit/third-party-notices as it makes integration simpler and more streamlined.
### Test plan

Build and install pods:
```
cd packages/test-app
yarn build --dependencies
pod install --project-directory=ios
```

Ran `yarn bundle` with these changes:
```diff
diff --git a/packages/test-app/package.json b/packages/test-app/package.json
index c651e9ae..3c25f2df 100644
--- a/packages/test-app/package.json
+++ b/packages/test-app/package.json
@@ -38,6 +38,7 @@
     "@rnx-kit/cli": "*",
     "@rnx-kit/metro-config": "*",
     "@rnx-kit/metro-plugin-cyclic-dependencies-detector": "*",
+    "@rnx-kit/third-party-notices": "*",
     "@rnx-kit/metro-plugin-duplicates-checker": "*",
     "@rnx-kit/metro-resolver-symlinks": "*",
     "@rnx-kit/metro-serializer": "*",
@@ -89,7 +90,14 @@
               ]
             }
           ],
-          "@rnx-kit/metro-plugin-typescript"
+          "@rnx-kit/metro-plugin-typescript",
+          [
+            "@rnx-kit/third-party-notices",
+            {
+              "rootPath": ".",
+              "sourceMapFile": "./dist/main.android.bundle.map"
+            }
+          ]
         ],
         "targets": [
           "android",
```

Example *.LICENSE.txt file generated:
[*.LICENSE.txt](https://github.com/microsoft/rnx-kit/files/10455109/main.android.bundle.LICENSE.txt)

2023-01-18 15:47 UTC, tido64 requested changes
Thanks for working on this @AAHAbbas :heart:

I left a few comments. You know where to find me if you have any questions. 😉

2023-01-18 15:47 UTC, tido64 commented on packages/third-party-notices/src/index.ts
> +    writeThirdPartyNotices(options);
I don't think we can call `writeThirdPartyNotices` here. At this point, the source map file has not been written to disk yet. However, you can extract modules from `graph` like we do in `metro-plugin-duplicates-checker`:

https://github.com/microsoft/rnx-kit/blob/f719c3dd52be7c2e154a43ea2dc8df6bcf425e5e/packages/metro-plugin-duplicates-checker/src/gatherModules.ts#L75-L81

You can probably copy `gatherModulesFromSources` and modify it to store the module path instead. This module map can then be fed directly to `extractLicenses`:

https://github.com/microsoft/rnx-kit/blob/f719c3dd52be7c2e154a43ea2dc8df6bcf425e5e/packages/third-party-notices/src/write-third-party-notices.ts#L54

Once you've done that, the `sourceMapFile` option should be redundant. I think we can also get `rootPath` from `options.projectRoot`.

2023-01-18 15:53 UTC, tido64 commented on packages/third-party-notices/src/index.ts
> +    writeThirdPartyNotices(options);
You should probably also use the source map location to determine the output path. For example:
```js
    const prefix = options.sourceMapUrl?.replace(/\.map$/, "") ?? "main";
    const outfile = prefix + ".LICENSE.txt";
```

2023-01-18 15:56 UTC, tido64 commented on packages/third-party-notices/src/index.ts
> +    writeThirdPartyNotices(options);
Another thing you should consider is whether you want to generate the TPN only when `options.dev` is false.

2023-01-19 12:31 UTC, tido64 commented on packages/third-party-notices/README.md
> ++    ]),
Do we need to update this now?

2023-01-19 12:31 UTC, tido64 commented on packages/third-party-notices/src/index.ts
> +export function ThirdPartyNotices(
Nit:
```suggestion
export { writeThirdPartyNotices } from "./write-third-party-notices";

export function ThirdPartyNotices(
```

2023-01-19 12:31 UTC, tido64 commented on packages/third-party-notices/src/index.ts
> +    if (!serializerOptions.dev) {
Shouldn't this be the other way around?
```suggestion
    if (serializerOptions.dev) {
```

2023-01-19 12:31 UTC, tido64 commented on packages/third-party-notices/src/write-third-party-notices.ts
> +import type { BasicSourceMap } from "metro-source-map";
Do we need to add `@types/metro-source-map` to `package.json` for this type?

2023-01-19 12:31 UTC, tido64 commented on packages/third-party-notices/src/write-third-party-notices.ts
> +  await writeFileAsync(outputFile, outputText, "utf8");
Can we use `fs.writeFileSync` here? It's going to be faster not to wait for a tick in Node.
```suggestion
  fs.writeFileSync(outputFile, outputText);
```

2023-01-19 12:31 UTC, tido64 commented on .changeset/clever-dancers-itch.md
> +Add metro plugin support for @rnx-kit/third-party-notices
This entry will be added to `@rnx-kit/third-party-notices`'s change log file. It's redundant to mention it again.

```suggestion
Add Metro plugin support
```

2023-01-19 12:58 UTC, AAHAbbas commented on packages/third-party-notices/README.md
> ++    ]),
Removed the changes.

2023-01-19 12:59 UTC, AAHAbbas commented on packages/third-party-notices/src/write-third-party-notices.ts
> +import type { BasicSourceMap } from "metro-source-map";
Right, added `@types/metro-source-map` and `@types/metro` to `devDependencies`.

2023-01-19 12:59 UTC, AAHAbbas commented on packages/third-party-notices/src/write-third-party-notices.ts
> +  await writeFileAsync(outputFile, outputText, "utf8");
Fixed.

2023-01-19 13:28 UTC, tido64 commented on packages/third-party-notices/README.md
> ++    ]),
I think we want to keep this. Just update the options.

2023-01-19 13:30 UTC, AAHAbbas commented on packages/third-party-notices/README.md
> ++    ]),
Ohh, I see. I'll fix it. Will remove the `rootPath` option.

2023-01-19 13:34 UTC, tido64 commented on packages/third-party-notices/README.md
> ++    ]),
Yeah, just reflect the latest changes 😄

2023-01-19 16:45 UTC, merged