feat(align-deps): Add core-visionos
microsoft/rnx-kit pull request #3073
Opened 2024-04-05 23:07 UTC by Saadnajmi

### Description

Add a `core-visionos` capability, and update the packages in the 0.73 profile to recommend versions with visionOS support.  

### Test plan

CI should pass

2024-04-08 09:54 UTC, kelset commented on packages/align-deps/src/presets/microsoft/react-native/profile-0.73.ts
> +    version: "^15.0.0",
this is a major bump, why is it needed?

2024-04-12 16:51 UTC, Saadnajmi commented on packages/align-deps/src/presets/microsoft/react-native/profile-0.73.ts
> +    version: "^15.0.0",
15.0.0 is the first version that supports visionOS

2024-04-12 16:53 UTC, Saadnajmi commented on packages/align-deps/src/presets/microsoft/react-native/profile-0.73.ts
> +    version: "^15.0.0",
So I thought I could make something like `profile-0.73-visionos` but that doesn't seem to be a thing. To update internal repos (which error if align-deps isn't happy), I wanted to add the `core-visions` capability and have it recommend the newer packages. It seems that not how capabilities work?

2024-04-12 17:01 UTC, Saadnajmi commented on packages/align-deps/src/presets/microsoft/react-native/profile-0.73.ts
> +    version: "^15.0.0",
Related, I've been holding off on this PR till some of my other PRs to add visionOS support land. But to unblock, I may split off the `0.73` profile updates to a separate PR

2024-04-12 20:25 UTC, Saadnajmi commented on packages/align-deps/src/presets/microsoft/react-native/profile-0.73.ts
> +    version: "^15.0.0",
https://github.com/microsoft/rnx-kit/pull/3085/

2024-05-22 06:26 UTC, tido64 commented on packages/align-deps/README.md
> +| core-visionos                        | Meta package for installing `react`                               | Meta package for installing `react`                               | Meta package for insta
Shouldn't this point to `react-native-visionos` at some point?

2024-05-22 18:42 UTC, Saadnajmi commented on packages/align-deps/README.md
> +| core-visionos                        | Meta package for installing `react`                               | Meta package for installing `react`                               | Meta package for insta
Hmm. I think this is because I put `#meta` for `profile-0.61.ts`

2024-05-22 19:12 UTC, tido64 requested changes

2024-05-22 19:12 UTC, tido64 commented on packages/align-deps/src/presets/microsoft/react-native/profile-0.73.ts
> +    name: "#meta",
Did we agree to use Callstack's as default?
```suggestion
    name: "@callstack/react-native-visionos",
```

2024-05-22 19:12 UTC, tido64 commented on packages/align-deps/src/presets/microsoft/react-native/profile-0.74.ts
> +    name: "#meta",
```suggestion
    name: "@callstack/react-native-visionos",
```

2024-06-03 11:17 UTC, tido64 commented on packages/test-app/package.json
> +        "core-visionos",
Reverting this change should make CI happy:
```suggestion
```

2024-06-03 11:32 UTC, tido64 approved these changes

2024-06-03 11:33 UTC, merged

2024-06-03 21:51 UTC, Saadnajmi commented on packages/test-app/package.json
> +        "core-visionos",
Oops, sorry I missed it. Thanks for checking!